security:
    encoders:
        App\Entity\Company:
            algorithm: bcrypt
            cost: 12

    providers:
        doctrine:
            entity:
                class: App\Entity\Company
                property: username

    firewalls:
        overview:
            pattern: ^/api$
            anonymous: true

        docs:
            pattern: ^/api/docs
            anonymous: true

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customers, roles: ROLE_COMPANY }
        - { path: ^/api/phones, roles: ROLE_COMPANY }
        - { path: ^/api/companies, roles: ROLE_COMPANY }
