# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Controller\addCustomerController:
        arguments:
            - '@lexik_jwt_authentication.security.guard.jwt_token_authenticator'
            - '@lexik_jwt_authentication.jwt_manager'

    Symfony\Component\HttpFoundation\Request:
        class: Symfony\Component\HttpFoundation\Request