# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Security\CompanyVoter:
        tags: ['security.voter']

    event_listener.resource.control_access:
        class: App\EventListener\ControlAccessListener
        arguments: ['@security.authorization_checker']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController ,priority: 12 }
